### PR TITLE
Update zlib-ng to 2.1.3

### PR DESCRIPTION
**Pull request by JakubOnderka**
zlib-ng 2.1.2 is the first stable release of the 2.1.x branch.

Most important optimizations and Enhancements:

* Decompression is a lot faster (56% faster measured on AVX2-capable x86-64)
* Compresson is improved for Level 9, at the cost of a little performance.
* Compression is improved for Level 3, by switching from deflate_fast to deflate_medium.

[Full changelog](https://github.com/zlib-ng/zlib-ng/releases/tag/2.1.2)

### CODE REVIEW

**Comment by JohnTitor** [comment]
Hm, I'm not sure if it's the fault of ctest but CI fails:
```sh
  D:\a\libz-sys\libz-sys\target\x86_64-pc-windows-msvc\debug\build\systest-zng-5622f69de174c92e\out\all.c(1295): warning C4047: 'return': 'int (__cdecl *)(zng_streamp,int,const char *,int)' differs in levels of indirection from 'int'
  D:\a\libz-sys\libz-sys\target\x86_64-pc-windows-msvc\debug\build\systest-zng-5622f69de174c92e\out\all.c(1300): error C2065: 'zng_deflateInit2_': undeclared identifier
  D:\a\libz-sys\libz-sys\target\x86_64-pc-windows-msvc\debug\build\systest-zng-5622f69de174c92e\out\all.c(1300): warning C4047: 'return': 'int (__cdecl *)(zng_streamp,int,int,int,int,int,const char *,int)' differs in levels of indirection from 'int'
  D:\a\libz-sys\libz-sys\target\x86_64-pc-windows-msvc\debug\build\systest-zng-5622f69de174c92e\out\all.c(1350): error C2065: 'zng_inflateBackInit_': undeclared identifier
  D:\a\libz-sys\libz-sys\target\x86_64-pc-windows-msvc\debug\build\systest-zng-5622f69de174c92e\out\all.c(1350): warning C4047: 'return': 'int (__cdecl *)(zng_streamp,int,unsigned char *,const char *,int)' differs in levels of indirection from 'int'
  D:\a\libz-sys\libz-sys\target\x86_64-pc-windows-msvc\debug\build\systest-zng-5622f69de174c92e\out\all.c(1370): error C2065: 'zng_inflateInit_': undeclared identifier
  D:\a\libz-sys\libz-sys\target\x86_64-pc-windows-msvc\debug\build\systest-zng-5622f69de174c92e\out\all.c(1370): warning C4047: 'return': 'int (__cdecl *)(zng_streamp,const char *,int)' differs in levels of indirection from 'int'
  D:\a\libz-sys\libz-sys\target\x86_64-pc-windows-msvc\debug\build\systest-zng-5622f69de174c92e\out\all.c(1375): error C2065: 'zng_inflateInit2_': undeclared identifier
  D:\a\libz-sys\libz-sys\target\x86_64-pc-windows-msvc\debug\build\systest-zng-5622f69de174c92e\out\all.c(1375): warning C4047: 'return': 'int (__cdecl *)(zng_streamp,int,const char *,int)' differs in levels of indirection from 'int'
```

**Comment by Byron** [comment]
Thanks for the update! I am quite new here and am as puzzled as you why these symbols would go missing all of the sudden. Is this something that reproduces locally?

**Comment by Byron** [comment]
Thanks so much!

CI is happy now and I wonder if that's all we need. Maybe there is other (avoidable) compatibility problems that arise when this crate is used by `flate2` or [other major dependents](https://crates.io/crates/libz-sys/reverse_dependencies)? It seems only manual testing can show what would happen, and I'd be satisfied knowing that `flate2` still works with this version of the crate, or that we are not missing anything here to maintain compatibility.

**Comment by thaliaarchi** [comment]
FYI, zlib-ng 2.1.3, which has now been released, is also marked as stable.

**Comment by Byron** [comment]
I'd be the first to want to merge this, and it all looks good to me, but that doesn't mean much.
Could I have another set of eyes?

**Review by Byron — APPROVED** [review]
I decided to fix my one issue, which was running tests through `flate2`. It turned out that what's on main doesn't actually compile for me, at least not on MacOS, whereas this branch works just fine. All `flate2` tests pass, and I wonder if I should adjust the CI to test `libz-sys` and `libz-ng-sys` with the latest version of `flate2` as well.

That way we could be more confident that nothing is broken, at least according to one of the main consumers of this crate.

In any case, I'd be willing to merge now.

**Comment by Byron** [comment]
With the additional testing in 5f2cf8d it turns out that what's in this PR is actually working with `flate2`, whereas what's in main causes failures with `zlib-ng` and `zlib-ng-compat` due to memory corruption.

Thus I will merge this PR now and see that I create a new point release.

**Comment by Byron** [comment]
[A new release](https://github.com/rust-lang/libz-sys/releases/tag/1.1.10) was published.

**Pull request merged**
