### PR TITLE
Use the latest build deps to fix builds on windows-2022

### PR DESCRIPTION
**Pull request by lespea**
Should fix https://github.com/rust-lang/libz-sys/issues/86

### CODE REVIEW

**Comment by lespea** [comment]
Seems like it's trying to build x64 library on the 686 targets?  I'll have to dig into this later tonight I was hoping it was a simple fix.

```
D:\a\libz-sys\libz-sys\target\i686-pc-windows-msvc\debug\deps\liblibz_sys-b077f531860f8372.rlib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'x86'
```

**Comment by Byron** [comment]
It breaks for me _now_ as well, but that might be unrelated to what this PR is fixing as this issue surfaced apparently with libz-sys 1.1.4.

I get `Error: could not find native static library `zlib`, perhaps an -L flag is missing?`, [here is the full log](https://github.com/Byron/gitoxide/runs/5456731713?check_suite_focus=true#step:7:353). Sorry for the noise if it's unrelated entirely.

**Comment by joshtriplett** [comment]
@lespea I'd appreciate your help fixing this issue. I think I've addressed all the other issues in CI other than this.

**Comment by lespea** [comment]
@joshtriplett I just made a new PR based off of the latest main branch: https://github.com/rust-lang/libz-sys/pull/92

**Comment by lespea** [comment]
@Byron you might need to install it via vcpkg?  Something like `vcpkg install zlib:x64-windows-static-md zlib:x86-windows-static` or `vcpkg install zlib:x64-windows-static-md zlib:x86-windows-static`.  I don't code in windows much but I had to install those when testing locally on my windows box.  I'm not sure which one exactly you need (`-md` or not) but obviously just choose the correct one for the architecture you're building.

**Comment by joshtriplett** [comment]
@lespea Thanks for the updated PR! I've merged that one to fix Windows builds of zlib-ng.

**Comment by Byron** [comment]
Thanks for the suggestions, @lespea , installing `zlib` like you suggested did indeed work for me :)!

**Pull request closed without merging**
