### PR TITLE
fix #149

### LINKED ISSUE #149: [libz-ng-sys] build for aarch64-linux-android
We need to modify `build.rs` to build `libz-ng-sys` for `aarch64-linux-android`:

```patch
diff '--color=auto' -ru -x Cargo.lock workdir-1/libz-ng-sys-1.1.12/build_zng.rs workdir/libz-ng-sys-1.1.12/build_zng.rs
--- workdir-1/libz-ng-sys-1.1.12/build_zng.rs	2023-08-21 15:28:56.175241480 +0800
+++ workdir/libz-ng-sys-1.1.12/build_zng.rs	2023-08-21 18:15:47.439786414 +0800
@@ -17,6 +17,10 @@
     if target == "i686-pc-windows-msvc" {
         cmake.define("CMAKE_GENERATOR_PLATFORM", "Win32");
     }
+    // Android
+    if target.contains("android") {
+        cmake.define("CMAKE_ANDROID_NDK", env::var("ANDROID_NDK_HOME").unwrap());
+    }
 
     let install_dir = cmake.build();
```

### PR DESCRIPTION
**Pull request by secext2022**
fix build for `aarch64-linux-android`

<https://github.com/rust-lang/libz-sys/issues/149>

### CODE REVIEW

**Comment by Byron** [comment]
Thanks a lot for submitting the PR. It looks like CI is happy. 
Would you be able to change the CI setup to include the `aarch64-linux-android` target?

**Comment by secext2022** [comment]
It seems that test with cross for android is error, so only build for android in CI.

**Comment by Byron** [comment]
The android tests look like they passed, and the other failures are spurious so I restarted them.
Once CI is green, could you do me a favour and unapply/revert the first commit temporarily so we see the android tests failing? That way we would validate that the android runs are actually catching the issue, which would mean that we will be warned of such issues in future as well.

Thanks a lot for your help.

**Comment by secext2022** [comment]
It seems that test in CI not work.
I'm trying to figure out why.

**Comment by secext2022** [comment]
Sorry, this is not a BUG of libz-ng-sys, it is my mistake.
I will explain this in detail in #149.

**Pull request closed without merging**
